table tb_rh
	lineageTag: fba9d14c-e0ff-4339-9176-b9fa54ed4062

	measure 'tt DE SALARIOS' = SUM(tb_rh[SALARIO])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1cd2c3ce-5f6f-4150-bd46-808666e49dd9

	measure ttdefaltas = SUM(tb_rh[QTDE FALTA])
		formatString: 0
		lineageTag: 26abf4a0-bcd4-46ca-8612-c698d87e3356

	measure genero = COUNT(tb_rh[NOME])
		formatString: 0
		lineageTag: db1a0c20-ccc6-468b-a947-e9faa1ae2af3

	measure 'idade por genero' = AVERAGE(tb_rh[IDADE])
		lineageTag: 2e6ddf8e-e517-4516-a45d-d33e99f154f7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 61019c4e-74b0-49b9-a357-22b2f43d353e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: d5f63716-1ebc-46ff-9581-0bec57fa8c47
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column IDADE
		dataType: int64
		formatString: 0
		lineageTag: f58b8281-cd8d-413a-8ffe-8426365755f5
		summarizeBy: sum
		sourceColumn: IDADE

		annotation SummarizationSetBy = Automatic

	column 'DATA ADIMISSAO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4f461a78-08bf-4b11-b00c-5dcce3b5f276
		summarizeBy: none
		sourceColumn: DATA ADIMISSAO

		variation Variation
			isDefault
			relationship: 57f2d528-2848-4d4a-9145-9902ba866416
			defaultHierarchy: LocalDateTable_b9b17793-dfcb-4070-99e1-05f8207dfd55.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DEPARTAMENTO
		dataType: string
		lineageTag: 07fbad6f-d778-48d6-a6e3-4e85b09a0c05
		summarizeBy: none
		sourceColumn: DEPARTAMENTO

		annotation SummarizationSetBy = Automatic

	column SALARIO
		dataType: int64
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 8b3b1bdb-5204-4142-8241-c26031a270f2
		summarizeBy: sum
		sourceColumn: SALARIO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'QTDE FALTA'
		dataType: int64
		formatString: 0
		lineageTag: b35eb263-f719-4f08-9bf1-e96740823ec9
		summarizeBy: sum
		sourceColumn: QTDE FALTA

		annotation SummarizationSetBy = Automatic

	column FILIAL
		dataType: string
		lineageTag: 947a3afe-04f8-4008-938a-933c454af189
		summarizeBy: none
		sourceColumn: FILIAL

		annotation SummarizationSetBy = Automatic

	column DEMISSOES
		dataType: string
		lineageTag: c1bf8cea-0da9-4a1c-9805-86bf7b0d9255
		summarizeBy: none
		sourceColumn: DEMISSOES

		annotation SummarizationSetBy = Automatic

	column SEXO
		dataType: string
		lineageTag: 75c6d014-6666-4641-a729-a1dd1af33fc7
		summarizeBy: none
		sourceColumn: SEXO

		annotation SummarizationSetBy = Automatic

	column 'CONTRATACÕES FEITAS'
		dataType: int64
		formatString: 0
		lineageTag: f8dbf2d6-a922-4cb4-849f-235dc037edc1
		summarizeBy: sum
		sourceColumn: CONTRATACÕES FEITAS

		annotation SummarizationSetBy = Automatic

	column ano = YEAR(tb_rh[DATA ADIMISSAO])
		formatString: 0
		lineageTag: f7543b17-d4b1-4041-b995-c9d4c209d139
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column FUNCIONARIO = IF(tb_rh[SALARIO] >= 5000 , "FUNCIONARIO CARO" , "FUNCIONARIO COMUM")
		lineageTag: 47b8c3fb-7128-4e21-8845-682c94863c76
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column estados =
			IF(tb_rh[FILIAL] = "RJ", "Rio de janeiro"
			, IF(tb_rh[FILIAL] = "SP", "Sao Paulo"
			, IF(tb_rh[FILIAL] = "MG", "Minas Gerais")))
		lineageTag: 7927fe66-b7cf-4955-bb86-f2bba9525eb0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column funcionario1 = IF(tb_rh[SALARIO] > 5000 && tb_rh[DEPARTAMENTO] = "GERENCIA" , "FUNCIONARIO CARO", "FUNCIONARIO COMUM")
		lineageTag: 9492fbb3-4822-4707-8ba2-267c16babe4b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column diaDaSemana = FORMAT(tb_rh[DATA ADIMISSAO] , "dd/mmm/yy")
		lineageTag: 25bf51b6-dfb9-49bf-a516-645ab89e8eca
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition tb_rh = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\User\Desktop\PowerBI\SALARIOS.xlsx"), null, true),
				    tb_rh_Table = Fonte{[Item="tb_rh",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(tb_rh_Table,{{"ID", Int64.Type}, {"NOME", type text}, {"IDADE", Int64.Type}, {"DATA ADIMISSAO", type date}, {"DEPARTAMENTO", type text}, {"SALARIO", Int64.Type}, {"QTDE FALTA", Int64.Type}, {"FILIAL", type text}, {"DEMISSOES", type text}, {"SEXO", type text}, {"CONTRATACÕES FEITAS", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

